### PR TITLE
Scripts for making paper numbers

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Review by vsoch — COMMENTED** [review]
Nice! What is missing is a "ho to run this stuff" in a README, but maybe what I can do (tomorrow) is try to run everything and take notes) and I'll ping you with questions. Does that worK?

Also I can give you a hacktoberfest point here - are you participating?

**Comment by hainest** [comment]
Yeah, I can put together a use guide. There are a few steps that are manual. I'd have to think about how those could be automated, if possible.

>Also I can give you a hacktoberfest point here - are you participating?

I was unaware of it, sooooo maybe?

**Comment by vsoch** [comment]
oh that would be great! Yeah ping me when you want me to test it out - that is probably easier than me guessing and borking it.

**Comment by vsoch** [comment]
okay added! Sign up here https://hacktoberfest.com/ and you only need 4 total before the end of October. If you just add the same label I did to PRs you opened in Dyninst recently you should be able to get them!

**Comment by vsoch** [comment]
our container build is good! 

https://github.com/buildsi/splice-experiment-results/actions/runs/3285013424/jobs/5411642712

@hainest whenever you are finished the analysis scripts, make sure to add the hashbang at the top for a python3 interpreter (from the environment) and run black on the scripts and we should be good to merge!

**Pull request merged**
